# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/exchange.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'v1/exchange.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11v1/exchange.proto\x12\x02v1\"\x8c\x01\n\x12\x43reateOrderRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x1b\n\x04type\x18\x02 \x01(\x0e\x32\r.v1.OrderType\x12\x1b\n\x04side\x18\x03 \x01(\x0e\x32\r.v1.OrderSide\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x01\x12\x12\n\x05price\x18\x05 \x01(\x01H\x00\x88\x01\x01\x42\x08\n\x06_price\"J\n\x13\x43reateOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"%\n\x13StreamTickerRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\"S\n\x06Ticker\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x0c\n\x04last\x18\x03 \x01(\x01\x12\x0b\n\x03\x62id\x18\x04 \x01(\x01\x12\x0b\n\x03\x61sk\x18\x05 \x01(\x01\"c\n\x11\x46\x65tchOHLCVRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x11\n\ttimeframe\x18\x02 \x01(\t\x12\r\n\x05since\x18\x03 \x01(\x03\x12\x12\n\x05limit\x18\x04 \x01(\x05H\x00\x88\x01\x01\x42\x08\n\x06_limit\"\'\n\x12\x46\x65tchOHLCVResponse\x12\x11\n\x05ohlcv\x18\x01 \x03(\x01\x42\x02\x10\x01*>\n\tOrderType\x12\x1a\n\x16ORDER_TYPE_UNSPECIFIED\x10\x00\x12\n\n\x06MARKET\x10\x01\x12\t\n\x05LIMIT\x10\x02*:\n\tOrderSide\x12\x1a\n\x16ORDER_SIDE_UNSPECIFIED\x10\x00\x12\x07\n\x03\x42UY\x10\x01\x12\x08\n\x04SELL\x10\x02\x32\xcb\x01\n\x0f\x45xchangeService\x12@\n\x0b\x43reateOrder\x12\x16.v1.CreateOrderRequest\x1a\x17.v1.CreateOrderResponse\"\x00\x12\x37\n\x0cStreamTicker\x12\x17.v1.StreamTickerRequest\x1a\n.v1.Ticker\"\x00\x30\x01\x12=\n\nFetchOHLCV\x12\x15.v1.FetchOHLCVRequest\x1a\x16.v1.FetchOHLCVResponse\"\x00\x42#Z!trading/robot/go-bot/gen/go/v1;v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.exchange_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z!trading/robot/go-bot/gen/go/v1;v1'
  _globals['_FETCHOHLCVRESPONSE'].fields_by_name['ohlcv']._loaded_options = None
  _globals['_FETCHOHLCVRESPONSE'].fields_by_name['ohlcv']._serialized_options = b'\020\001'
  _globals['_ORDERTYPE']._serialized_start=510
  _globals['_ORDERTYPE']._serialized_end=572
  _globals['_ORDERSIDE']._serialized_start=574
  _globals['_ORDERSIDE']._serialized_end=632
  _globals['_CREATEORDERREQUEST']._serialized_start=26
  _globals['_CREATEORDERREQUEST']._serialized_end=166
  _globals['_CREATEORDERRESPONSE']._serialized_start=168
  _globals['_CREATEORDERRESPONSE']._serialized_end=242
  _globals['_STREAMTICKERREQUEST']._serialized_start=244
  _globals['_STREAMTICKERREQUEST']._serialized_end=281
  _globals['_TICKER']._serialized_start=283
  _globals['_TICKER']._serialized_end=366
  _globals['_FETCHOHLCVREQUEST']._serialized_start=368
  _globals['_FETCHOHLCVREQUEST']._serialized_end=467
  _globals['_FETCHOHLCVRESPONSE']._serialized_start=469
  _globals['_FETCHOHLCVRESPONSE']._serialized_end=508
  _globals['_EXCHANGESERVICE']._serialized_start=635
  _globals['_EXCHANGESERVICE']._serialized_end=838
# @@protoc_insertion_point(module_scope)
