# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from v1 import exchange_pb2 as v1_dot_exchange__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in v1/exchange_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExchangeServiceStub(object):
    """ExchangeService defines the gRPC service for interacting with a cryptocurrency exchange.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateOrder = channel.unary_unary(
                '/v1.ExchangeService/CreateOrder',
                request_serializer=v1_dot_exchange__pb2.CreateOrderRequest.SerializeToString,
                response_deserializer=v1_dot_exchange__pb2.CreateOrderResponse.FromString,
                _registered_method=True)
        self.StreamTicker = channel.unary_stream(
                '/v1.ExchangeService/StreamTicker',
                request_serializer=v1_dot_exchange__pb2.StreamTickerRequest.SerializeToString,
                response_deserializer=v1_dot_exchange__pb2.Ticker.FromString,
                _registered_method=True)
        self.FetchOHLCV = channel.unary_unary(
                '/v1.ExchangeService/FetchOHLCV',
                request_serializer=v1_dot_exchange__pb2.FetchOHLCVRequest.SerializeToString,
                response_deserializer=v1_dot_exchange__pb2.FetchOHLCVResponse.FromString,
                _registered_method=True)


class ExchangeServiceServicer(object):
    """ExchangeService defines the gRPC service for interacting with a cryptocurrency exchange.
    """

    def CreateOrder(self, request, context):
        """CreateOrder places a new order on the exchange.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTicker(self, request, context):
        """StreamTicker streams real-time ticker information for a given symbol.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchOHLCV(self, request, context):
        """FetchOHLCV fetches historical Open, High, Low, Close, Volume data.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExchangeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrder,
                    request_deserializer=v1_dot_exchange__pb2.CreateOrderRequest.FromString,
                    response_serializer=v1_dot_exchange__pb2.CreateOrderResponse.SerializeToString,
            ),
            'StreamTicker': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTicker,
                    request_deserializer=v1_dot_exchange__pb2.StreamTickerRequest.FromString,
                    response_serializer=v1_dot_exchange__pb2.Ticker.SerializeToString,
            ),
            'FetchOHLCV': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchOHLCV,
                    request_deserializer=v1_dot_exchange__pb2.FetchOHLCVRequest.FromString,
                    response_serializer=v1_dot_exchange__pb2.FetchOHLCVResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'v1.ExchangeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('v1.ExchangeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExchangeService(object):
    """ExchangeService defines the gRPC service for interacting with a cryptocurrency exchange.
    """

    @staticmethod
    def CreateOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ExchangeService/CreateOrder',
            v1_dot_exchange__pb2.CreateOrderRequest.SerializeToString,
            v1_dot_exchange__pb2.CreateOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTicker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/v1.ExchangeService/StreamTicker',
            v1_dot_exchange__pb2.StreamTickerRequest.SerializeToString,
            v1_dot_exchange__pb2.Ticker.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchOHLCV(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ExchangeService/FetchOHLCV',
            v1_dot_exchange__pb2.FetchOHLCVRequest.SerializeToString,
            v1_dot_exchange__pb2.FetchOHLCVResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
