# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from v1 import exchange_pb2 as v1_dot_exchange__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in v1/exchange_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExchangeServiceStub(object):
    """ExchangeService defines the gRPC service for interacting with a cryptocurrency exchange.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/v1.ExchangeService/Ping',
                request_serializer=v1_dot_exchange__pb2.PingRequest.SerializeToString,
                response_deserializer=v1_dot_exchange__pb2.PingResponse.FromString,
                _registered_method=True)
        self.GetTicker = channel.unary_unary(
                '/v1.ExchangeService/GetTicker',
                request_serializer=v1_dot_exchange__pb2.GetTickerRequest.SerializeToString,
                response_deserializer=v1_dot_exchange__pb2.TickerResponse.FromString,
                _registered_method=True)
        self.GetBalance = channel.unary_unary(
                '/v1.ExchangeService/GetBalance',
                request_serializer=v1_dot_exchange__pb2.GetBalanceRequest.SerializeToString,
                response_deserializer=v1_dot_exchange__pb2.BalanceResponse.FromString,
                _registered_method=True)
        self.CreateOrder = channel.unary_unary(
                '/v1.ExchangeService/CreateOrder',
                request_serializer=v1_dot_exchange__pb2.CreateOrderRequest.SerializeToString,
                response_deserializer=v1_dot_exchange__pb2.OrderResponse.FromString,
                _registered_method=True)
        self.CancelOrder = channel.unary_unary(
                '/v1.ExchangeService/CancelOrder',
                request_serializer=v1_dot_exchange__pb2.CancelOrderRequest.SerializeToString,
                response_deserializer=v1_dot_exchange__pb2.CancelOrderResponse.FromString,
                _registered_method=True)
        self.GetOrder = channel.unary_unary(
                '/v1.ExchangeService/GetOrder',
                request_serializer=v1_dot_exchange__pb2.GetOrderRequest.SerializeToString,
                response_deserializer=v1_dot_exchange__pb2.OrderResponse.FromString,
                _registered_method=True)
        self.GetOpenOrders = channel.unary_unary(
                '/v1.ExchangeService/GetOpenOrders',
                request_serializer=v1_dot_exchange__pb2.GetOrdersRequest.SerializeToString,
                response_deserializer=v1_dot_exchange__pb2.OrdersResponse.FromString,
                _registered_method=True)
        self.GetRecentTrades = channel.unary_unary(
                '/v1.ExchangeService/GetRecentTrades',
                request_serializer=v1_dot_exchange__pb2.GetOrdersRequest.SerializeToString,
                response_deserializer=v1_dot_exchange__pb2.OrdersResponse.FromString,
                _registered_method=True)
        self.ResetState = channel.unary_unary(
                '/v1.ExchangeService/ResetState',
                request_serializer=v1_dot_exchange__pb2.ResetStateRequest.SerializeToString,
                response_deserializer=v1_dot_exchange__pb2.ResetStateResponse.FromString,
                _registered_method=True)


class ExchangeServiceServicer(object):
    """ExchangeService defines the gRPC service for interacting with a cryptocurrency exchange.
    """

    def Ping(self, request, context):
        """Ping is a simple health check method to verify that the gateway is alive
        and can communicate with the exchange.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTicker(self, request, context):
        """GetTicker fetches the current price for a given symbol.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBalance(self, request, context):
        """GetBalance fetches the account balance.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateOrder(self, request, context):
        """CreateOrder places a new order on the exchange.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelOrder(self, request, context):
        """CancelOrder cancels an existing order.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrder(self, request, context):
        """GetOrder fetches details of a specific order.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOpenOrders(self, request, context):
        """GetOpenOrders fetches all open orders for a symbol.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecentTrades(self, request, context):
        """GetRecentTrades fetches recent execution history for a symbol.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetState(self, request, context):
        """ResetState resets the state of the exchange.
        WARN: This method is intended for testing purposes only.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExchangeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=v1_dot_exchange__pb2.PingRequest.FromString,
                    response_serializer=v1_dot_exchange__pb2.PingResponse.SerializeToString,
            ),
            'GetTicker': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTicker,
                    request_deserializer=v1_dot_exchange__pb2.GetTickerRequest.FromString,
                    response_serializer=v1_dot_exchange__pb2.TickerResponse.SerializeToString,
            ),
            'GetBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBalance,
                    request_deserializer=v1_dot_exchange__pb2.GetBalanceRequest.FromString,
                    response_serializer=v1_dot_exchange__pb2.BalanceResponse.SerializeToString,
            ),
            'CreateOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrder,
                    request_deserializer=v1_dot_exchange__pb2.CreateOrderRequest.FromString,
                    response_serializer=v1_dot_exchange__pb2.OrderResponse.SerializeToString,
            ),
            'CancelOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelOrder,
                    request_deserializer=v1_dot_exchange__pb2.CancelOrderRequest.FromString,
                    response_serializer=v1_dot_exchange__pb2.CancelOrderResponse.SerializeToString,
            ),
            'GetOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrder,
                    request_deserializer=v1_dot_exchange__pb2.GetOrderRequest.FromString,
                    response_serializer=v1_dot_exchange__pb2.OrderResponse.SerializeToString,
            ),
            'GetOpenOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOpenOrders,
                    request_deserializer=v1_dot_exchange__pb2.GetOrdersRequest.FromString,
                    response_serializer=v1_dot_exchange__pb2.OrdersResponse.SerializeToString,
            ),
            'GetRecentTrades': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecentTrades,
                    request_deserializer=v1_dot_exchange__pb2.GetOrdersRequest.FromString,
                    response_serializer=v1_dot_exchange__pb2.OrdersResponse.SerializeToString,
            ),
            'ResetState': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetState,
                    request_deserializer=v1_dot_exchange__pb2.ResetStateRequest.FromString,
                    response_serializer=v1_dot_exchange__pb2.ResetStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'v1.ExchangeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('v1.ExchangeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExchangeService(object):
    """ExchangeService defines the gRPC service for interacting with a cryptocurrency exchange.
    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ExchangeService/Ping',
            v1_dot_exchange__pb2.PingRequest.SerializeToString,
            v1_dot_exchange__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTicker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ExchangeService/GetTicker',
            v1_dot_exchange__pb2.GetTickerRequest.SerializeToString,
            v1_dot_exchange__pb2.TickerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ExchangeService/GetBalance',
            v1_dot_exchange__pb2.GetBalanceRequest.SerializeToString,
            v1_dot_exchange__pb2.BalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ExchangeService/CreateOrder',
            v1_dot_exchange__pb2.CreateOrderRequest.SerializeToString,
            v1_dot_exchange__pb2.OrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ExchangeService/CancelOrder',
            v1_dot_exchange__pb2.CancelOrderRequest.SerializeToString,
            v1_dot_exchange__pb2.CancelOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ExchangeService/GetOrder',
            v1_dot_exchange__pb2.GetOrderRequest.SerializeToString,
            v1_dot_exchange__pb2.OrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOpenOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ExchangeService/GetOpenOrders',
            v1_dot_exchange__pb2.GetOrdersRequest.SerializeToString,
            v1_dot_exchange__pb2.OrdersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRecentTrades(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ExchangeService/GetRecentTrades',
            v1_dot_exchange__pb2.GetOrdersRequest.SerializeToString,
            v1_dot_exchange__pb2.OrdersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ExchangeService/ResetState',
            v1_dot_exchange__pb2.ResetStateRequest.SerializeToString,
            v1_dot_exchange__pb2.ResetStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
